### ISSUE TITLE
Configurable maximum attachment size

### ISSUE THREAD

**Issue by kalvdans** [waldner/snappymail-docker#1]
The maximum attachment one can send is now 2 MB, which is a bit small.

See https://github.com/phpmyadmin/docker/blob/master/Dockerfile-alpine.template for an example how to adapt php.ini to allow larger uploads. (Source: https://github.com/the-djmaze/snappymail/issues/1683)

**Comment by waldner** [comment]
Ok, fair enough. I'm just checking the status of things and I see that docker hub no longer has automated builds in the free plan, and php and snappymail have newer version, so I'm going to fix all these things too. It'll take a few days.

**Comment by kalvdans** [comment]
no hurry, and I can give it a shot as well when I find time. I just filed the issue to not forget about it.. don't take it as a demand for you to do work!

**Comment by waldner** [comment]
This should be fixed (among other things) by https://github.com/waldner/snappymail-docker/commit/8ecc6989f277d5185169afe33ce21479dce8657a, you just need to set  `UPLOAD_MAX_SIZE=XXm` in your `.env` (default is 10m anyway). Give it a go.

**Comment by kalvdans** [comment]
Thanks a lot!
It refuses to start for me, the logs show the error:
```
nginx: [emerg] invalid number of arguments in "client_max_body_size" directive in /etc/nginx/http.d/default.conf:52
```

my docker-compose.yml:
```
version: "3.3"

services:
  snappymail:
    image: ghcr.io/waldner/snappymail-docker:latest
    container_name: snappymail
    hostname: snappymail
    restart: always
    volumes:
      - /srv/docker-data/snappymail:/snappymail/data
    ports:
      - 8090:80
    environment:
      - TZ=UTC
      - USE_SSL=0
```
